spring:
  application:
    name: system

#服务端口
server:
  port: 9101

#注册到服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true